
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/tacho/Desktop/micro/TBA1/front/build/assets/frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#B1CCFF")


canvas = Canvas(
    window,
    bg = "#B1CCFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1462.0,
    1662.5777587890625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    64.0,
    28.0,
    1399.0,
    986.0,
    fill="#000000",
    outline="")

canvas.create_text(
    44.0,
    112.0,
    anchor="nw",
    text="Nombre Apellido",
    fill="#FFFFFF",
    font=("ArialMT", 32 * -1)
)

canvas.create_rectangle(
    138.0,
    47.0,
    186.0,
    95.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    411.0,
    100.0,
    1334.0,
    139.0,
    fill="#142D5D",
    outline="")

canvas.create_rectangle(
    411.0,
    200.0,
    1334.0,
    261.0,
    fill="#152D5D",
    outline="")

canvas.create_text(
    432.0,
    106.0,
    anchor="nw",
    text="Dato",
    fill="#FFFFFF",
    font=("ArialMT", 24 * -1)
)

canvas.create_text(
    432.0,
    158.0,
    anchor="nw",
    text="Temperatura",
    fill="#FFFFFF",
    font=("ArialMT", 20 * -1)
)

canvas.create_text(
    809.0,
    106.0,
    anchor="nw",
    text="Valor Actual",
    fill="#FFFFFF",
    font=("ArialMT", 24 * -1)
)

canvas.create_text(
    809.0,
    158.0,
    anchor="nw",
    text="38°C",
    fill="#FFFFFF",
    font=("ArialMT", 20 * -1)
)

canvas.create_text(
    1040.0,
    106.0,
    anchor="nw",
    text="Importancia",
    fill="#FFFFFF",
    font=("ArialMT", 24 * -1)
)

canvas.create_text(
    1040.0,
    158.0,
    anchor="nw",
    text="Importante",
    fill="#FFFFFF",
    font=("ArialMT", 20 * -1)
)

canvas.create_text(
    1222.0,
    106.0,
    anchor="nw",
    text="¿Acción?",
    fill="#FFFFFF",
    font=("ArialMT", 24 * -1)
)

canvas.create_rectangle(
    1140.0,
    166.0,
    1150.0,
    176.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1222.0,
    156.0,
    1323.0,
    185.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
