
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/tacho/Desktop/micro/TBA1/front/build/assets/frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#B1CCFF")


canvas = Canvas(
    window,
    bg = "#B1CCFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    369.0,
    28.0,
    1399.0,
    986.0,
    fill="#153573",
    outline="")

canvas.create_rectangle(
    532.0,
    306.0,
    863.0,
    777.0,
    fill="#142D5D",
    outline="")

canvas.create_rectangle(
    571.0,
    349.0,
    825.0,
    735.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    656.0,
    246.0,
    anchor="nw",
    text="WIFI",
    fill="#FFFFFF",
    font=("Arial BoldMT", 40 * -1)
)

canvas.create_rectangle(
    896.0,
    306.0,
    1227.0,
    777.0,
    fill="#142D5D",
    outline="")

canvas.create_rectangle(
    935.0,
    349.0,
    1189.0,
    735.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    1020.0,
    246.0,
    anchor="nw",
    text="USB",
    fill="#FFFFFF",
    font=("Arial BoldMT", 40 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    323.0,
    1024.0,
    fill="#153573",
    outline="")

canvas.create_rectangle(
    0.0,
    952.0,
    323.0,
    1024.0,
    fill="#0C2658",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=68.0,
    y=973.0,
    width=185.0,
    height=36.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=0.0,
    y=251.0,
    width=323.0,
    height=41.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=0.0,
    y=302.0,
    width=323.0,
    height=41.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=0.0,
    y=353.0,
    width=323.0,
    height=41.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=0.0,
    y=404.0,
    width=323.0,
    height=41.0
)

canvas.create_text(
    44.0,
    112.0,
    anchor="nw",
    text="Nombre Apellido",
    fill="#FFFFFF",
    font=("ArialMT", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
